name: OpenAI API Integration

on:
  push:
    branches:
      - main

jobs:
  call_openai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call OpenAI API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          curl https://api.openai.com/v1/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -d '{
            "model": "text-davinci-003",
            "prompt": "Write a Git commit message for the recent changes",
            "max_tokens": 50
          }' | jq '.choices[0].text'
